version: "3.8"
services:
    nodejs:
        build:
            context: ./app
        image: "prashansa_nodejs"
        ports:
            - "8000:8000"
    nginx:
        restart: always
        image: "prashansa_nginx"
        build:
            context: ./nginx
        ports:
            - "80:80"
        depends_on:
            - nodejs